<a href="https://colab.research.google.com/github/Jinnkazuma/dataML/blob/main/Copia_de_NumPy_Exercises_for_Data_Analysis_CGAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [2]:
# Import numpy as np and see the version
import numpy as np
!python
# your code here
pass

Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
KeyboardInterrupt
>>> 
KeyboardInterrupt
>>> 
KeyboardInterrupt
>>> ^C


In [ ]:
# Create a 1D array of numbers from 0 to 9
newArray=np.array(range(10))
print(newArray)
print(type(newArray))
# your code here
pass

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
# Create random vector of size 10 and replace the maximum value by 0
# Create a random vector of size 10
vector = np.random.randint(1,10,size=(10))

# Replace the maximum value with 0
vector[vector.argmax()] = 0

print(vector)
pass

[7 3 1 6 7 0 3 3 8 5]


In [ ]:
# Print the number 8 from the array below:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

# Print the number 8
print(arr[1,2])
pass

8


In [ ]:
# Print the numbers [3, 4, 5] from the array below:
arr = np.array([1,2,3,4,5,6,7])
print(arr[2:5])
pass

[3 4 5]


In [ ]:
# Print the last 4 numbers from the array below:
arr = np.array([1,2,3,4,5,6,7])
print(arr[-4:])
pass

[4 5 6 7]


In [ ]:
# Create a 3×3 numpy array of all True’s
# your code here
array = np.ones((3, 3), dtype=bool)
print(array)
pass

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Extract all odd numbers from arr
# your code here
odd_numbers = arr[np.where(arr % 2 != 0)]
print(odd_numbers)
pass

[1 3 5 7 9]


In [ ]:
# Create a vector with values ranging from 10 to 49 (★☆☆)
vector = np.arange(10, 50)

print(vector)
pass


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# Reverse a vector (first element becomes last)
vector = np.array([1, 2, 3, 4, 5])

# Reverse the vector using slicing
reversed_vector = vector[::-1]

print(reversed_vector)

pass

[5 4 3 2 1]


In [ ]:
vector = np.array([1, 2, 3, 4, 5])

# Reverse the vector using slicing
reversed_vector = vector[::-1]

print(reversed_vector)
pass

[5 4 3 2 1]


In [ ]:
# Create a 3x3x3 array with random values
array = np.random.randint(1, 10, size=(3, 3, 3))
print(array)
pass

[[[6 2 8]
  [4 9 5]
  [2 2 7]]

 [[9 7 5]
  [4 3 5]
  [3 5 8]]

 [[7 9 6]
  [3 3 2]
  [9 2 6]]]


In [ ]:
# Replace all odd numbers in arr with -1
# your code here
arr = np.array([1, 2, 3, 4, 5])
arr[arr % 2 != 0] = -1

print(arr)
pass

[-1  2 -1  4 -1]


In [ ]:
# Create an array of type float
array=np.random.rand(5)
print(array)
pass

[0.33670024 0.7196454  0.26560188 0.95987208 0.62652661]


In [3]:
# Convert a 1D array to a 2D array with 2 rows
# your code here

array = np.array([1, 2, 3, 4, 5, 6])

array_2d = array.reshape((2, 3))

print(array_2d)

pass

[[1 2 3]
 [4 5 6]]


In [6]:
# How to find common values between two arrays?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

#A
common_values = np.intersect1d(Z1, Z2)
print(common_values)

#B
common_values = Z1[np.isin(Z1, Z2)]
print(common_values)




pass

[0 3 5 7 9]
[7 3 7 9 7 3 5 0]


In [8]:
#  Consider two random array A and B, check if they are equal


A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Check if the two arrays are equal
if np.array_equal(A, B):
    print("The two arrays are equal.")
else:
    print("The two arrays are not equal.")
pass

The two arrays are not equal.


In [ ]:
# Stack arrays a and b vertically
# your code here

a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
c = np.array([11, 12, 13, 14, 15])

# Stack the three arrays vertically
d = np.vstack((a, b, c))

print(d)
pass

In [9]:
# Stack the arrays a and b horizontally.
# your code here
# Create two 1D arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

# Stack the two arrays horizontally
c = np.hstack((a, b))

print(c)
pass

[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
# Get all items between 5 and 10 from array tmp.
# your code here
import numpy as np
tmp = np.arange(15)

# Get all items between 5 and 10 from array tmp
items_between_5_and_10 = tmp[(tmp >= 5) & (tmp < 10)]

print(items_between_5_and_10)

# pass

[5 6 7 8 9]


In [14]:
# How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here
import numpy as np

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
print('-----------------')

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

# Vectorize the maxx() function
maxx_vectorized = np.vectorize(maxx)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# Get the maximum of two NumPy arrays
c = maxx_vectorized(a, b)

print(c)


-----------------
[6 7 9 8 9 7 5]


In [15]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


arr = np.arange(9).reshape(3,3)
print(arr)
# your code here

arr = np.arange(9).reshape(3,3)

arr[:, [1, 2]] = arr[:, [2, 1]]

print(arr)
pass


[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [ ]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

random_array = np.random.rand(5, 3) * 5 + 5

print(random_array)

[[9.15249585 7.93877525 7.34871195]
 [7.046033   5.22641792 5.76397407]
 [9.2925807  9.56199446 6.07821952]
 [7.00703533 9.04454438 7.46340573]
 [8.64972094 5.41144492 5.32995681]]
