<a href="https://colab.research.google.com/github/Jinnkazuma/dataML/blob/main/ejerciciosMatrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [ ]:
a = np.random.randint(1,11, size=(3,4))
b = np.random.randint(1,11, size=(3,4))
print(a)
print(a.shape)
print("------------")
print(b)
print(b.shape)
print("------------")
print('adding numbers')
print(a+b)
print("------------")
print('subtracting numbers')
print(a-b)
print("------------")
print('Multiplicación numbers')
print(a*b)
print(np.add(a,b))
print(np.multiply(a,b))

print('divide numbers')
print(np.add(a,b))
print(np.divide(a,b))

[[ 2 10  7  5]
 [ 1  9 10  8]
 [ 3  4  3  4]]
(3, 4)
------------
[[10  8  3  9]
 [ 7 10  4  7]
 [ 5  9  7  7]]
(3, 4)
------------
adding numbers
[[12 18 10 14]
 [ 8 19 14 15]
 [ 8 13 10 11]]
------------
subtracting numbers
[[-8  2  4 -4]
 [-6 -1  6  1]
 [-2 -5 -4 -3]]
------------
Multiplicación numbers
[[20 80 21 45]
 [ 7 90 40 56]
 [15 36 21 28]]
[[12 18 10 14]
 [ 8 19 14 15]
 [ 8 13 10 11]]
[[20 80 21 45]
 [ 7 90 40 56]
 [15 36 21 28]]
divide numbers
[[12 18 10 14]
 [ 8 19 14 15]
 [ 8 13 10 11]]
[[0.2        1.25       2.33333333 0.55555556]
 [0.14285714 0.9        2.5        1.14285714]
 [0.6        0.44444444 0.42857143 0.57142857]]


In [ ]:
x = np.random.randint(1,11, size=(2,3))
z = np.random.randint(1,11, size=(3,4))
print("matriz x")
print(x)
print(x.shape)
print("------------------------")
print("matriz z")
print(z)
print(z.shape)
print("------------------------")
print("resultado de la multiplicacion de la matriz")
print(np.dot(x,z))
print("------------------------")
print("x.dot(z)")
print(x.dot(z))

matriz x
[[ 8  7  7]
 [ 9 10  6]]
(2, 3)
------------------------
matriz z
[[4 3 4 1]
 [7 6 7 7]
 [8 7 4 8]]
(3, 4)
------------------------
resultado de la multiplicacion de la matriz
[[137 115 109 113]
 [154 129 130 127]]
------------------------
x.dot(z)
[[137 115 109 113]
 [154 129 130 127]]


In [ ]:
print("obtener la matriz copuesta")
x = np.random.randint(1,11, size=(2,3))
print(x.shape)
print(type(x))
print(x)
print(x.T)

obtener la matriz copuesta
(2, 3)
<class 'numpy.ndarray'>
[[6 6 9]
 [4 3 7]]
[[6 4]
 [6 3]
 [9 7]]


In [5]:
print("Prodcast")
a = np.random.randint(1,11, size=(4,3))
b = np.random.randint(1,11, size=(4,3))
print(a.shape)

c=np.empty_like(a)

print(b.shape)
print("----------")
print(b)


Prodcast
(4, 3)
(4, 3)
----------
[[7 9 2]
 [4 4 2]
 [8 3 5]
 [8 2 3]]


In [ ]:
# Crear una matriz de 6x3 con valores 1, 2 y 3
valores = [1, 2, 3]
a = np.full((6, 3), valores)

# Imprimir la matriz
print(a)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [8]:
import numpy as np

# Valores a repetir en la matriz
a = np.array([1, 2, 3])

# Crear una matriz de 6x3 repitiendo los valores
b = np.tile(a, (6, 1))

# Imprimir la matriz
print(b)


[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [9]:
a=np.array([1,2,3])
print(a)
tmp=np.tile(a,(6,1))
print(tmp)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [10]:
print("Promedio de todos los elementos de una matriz")
q = np.random.randint(20,31, size=(6,6))
print(q)
aux=np.mean(q)
print("promedio: ",aux)

# Calcula el promedio por fila
fila = np.mean(q, axis=1)
print("Promedio por fila: ",fila)

# Calcula el promedio por columna
columna = np.mean(q, axis=0)
print("Promedio por columna: ",columna)

Promedio de todos los elementos de una matriz
[[27 29 23 25 21 21]
 [23 20 29 29 30 24]
 [26 26 23 20 22 20]
 [24 29 24 28 29 30]
 [20 26 26 29 30 21]
 [22 27 23 26 22 28]]
promedio:  25.055555555555557
Promedio por fila:  [24.33333333 25.83333333 22.83333333 27.33333333 25.33333333 24.66666667]
Promedio por columna:  [23.66666667 26.16666667 24.66666667 26.16666667 25.66666667 24.        ]


In [11]:
print("Promedio de todos los elementos de una matriz")
q = np.random.randint(20,31, size=(6,6))
print(q)
aux=np.mean(q)
print("promedio: ",aux)

print(q.mean(axis=1))

Promedio de todos los elementos de una matriz
[[26 30 24 20 24 21]
 [21 26 27 25 28 23]
 [28 25 24 26 28 24]
 [26 25 21 25 27 29]
 [29 27 27 20 24 27]
 [30 22 22 25 26 21]]
promedio:  25.083333333333332
[24.16666667 25.         25.83333333 25.5        25.66666667 24.33333333]
