<a href="https://colab.research.google.com/github/Jinnkazuma/dataML/blob/main/Exercises_about_Pandas_Lib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
aux=np.array([1,2,3,4,5])
print(aux)
print(aux.shape)

aux2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(aux2)
print(aux2.shape)
print(type(aux2))

[1 2 3 4 5]
(5,)
[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)
<class 'numpy.ndarray'>


In [ ]:
tmp=np.zeros((4,4))
print(tmp)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
print("Matriz full valores del mismo numeroi")
tmp=np.full((4,4),5)
print(tmp)

Matriz full valores del mismo numeroi
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
print("Matriz diagonal")
tmp=np.eye(4,4)
print(tmp)

Matriz diagonal
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print("Matriz de 1")
tmp=np.ones((4,4))
print(tmp)

Matriz de 1
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
print("Numeros randoms")
tmp=10*np.random.random((4,4))
print(tmp)
print(tmp.shape)

Numeros randoms
[[3.87099725 8.37772372 0.96533027 0.0831836 ]
 [3.14379169 7.36991391 8.92648052 7.63092693]
 [3.59465839 6.67740175 8.70065556 5.32584737]
 [9.49497603 8.33375357 8.71878096 2.5746137 ]]
(4, 4)


In [ ]:
print(tmp[:2,:2])

[[3.87099725 8.37772372]
 [3.14379169 7.36991391]]


In [ ]:
print(tmp[:2,1:3])

[[8.37772372 0.96533027]
 [7.36991391 8.92648052]]


In [ ]:
print(tmp[3])

[9.49497603 8.33375357 8.71878096 2.5746137 ]


In [ ]:
print(tmp[2,2])

8.700655560091976


In [ ]:
print("Numeros randoms")
tmp=10*np.random.random((4,4))
print(tmp)
print(tmp.shape)

Numeros randoms
[[2.737012   5.11718879 3.45754038 6.93055782]
 [3.56688244 3.21072693 8.05972576 2.27792374]
 [3.52822103 4.12165481 3.40329619 8.46346545]
 [1.77995471 9.00676864 8.11754713 6.10598652]]
(4, 4)


In [ ]:
mask=tmp>5
print(tmp[mask])

[5.11718879 6.93055782 8.05972576 8.46346545 9.00676864 8.11754713
 6.10598652]


In [ ]:
mask=(tmp>=2)&(tmp<=4)
print(tmp[mask])

[2.737012   3.45754038 3.56688244 3.21072693 2.27792374 3.52822103
 3.40329619]


In [ ]:
# Crear un arreglo de 4x4 con valores aleatorios enteros entre 1 y 100
arreglo = np.random.randint(1, 101, size=(4, 4))

print("Arreglo original:")
print(arreglo)

# Crear una máscara booleana para los números pares
mascara_pares = arreglo % 2 == 0

# Aplicar la máscara para seleccionar los números pares
numeros_pares = arreglo[mascara_pares]

print("Números pares:")
print(numeros_pares)

Arreglo original:
[[87 56 44 29]
 [26 82 15 50]
 [87 43 90 81]
 [97 44 88 53]]
Números pares:
[56 44 26 82 50 90 44 88]
